name: Post Ops Jobs to Discord

on:
  schedule:
    # Runs daily at 7 AM EDT (11 AM UTC)
    - cron: '0 11 * * *'
  workflow_dispatch:  # Allows manual triggering for testing

jobs:
  post-ops-jobs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install requests
      
      - name: Debug - Check secrets availability
        run: |
          echo "Checking if secrets are available..."
          if [ -z "${{ secrets.HIREBASE_API_KEY }}" ]; then
            echo "❌ HIREBASE_API_KEY secret is not set"
          else
            echo "✅ HIREBASE_API_KEY is available"
          fi
          
          if [ -z "${{ secrets.DISCORD_OPS_HOOK }}" ]; then
            echo "❌ DISCORD_OPS_HOOK secret is not set"
          else
            echo "✅ DISCORD_OPS_HOOK is available"
          fi
      
      - name: Run job posting script
        env:
          HIREBASE_API_KEY: ${{ secrets.HIREBASE_API_KEY }}
          DISCORD_OPS_HOOK: ${{ secrets.DISCORD_OPS_HOOK }}
        run: python post_ops_jobs.py
      
      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ops-error-logs
          path: '*.log'
          retention-days: 7